//! Test helpers: float32 fixtures generated by `bench/audio-enhance/make_rust_fixtures.py`.
use std::path::PathBuf;

pub fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/enhance")
}

/// Returns (data, shape).
pub fn fixture(name: &str) -> (Vec<f32>, Vec<usize>) {
    let dir = fixture_dir();
    let bytes = std::fs::read(dir.join(format!("{name}.f32"))).expect("fixture");
    let data = bytes.chunks_exact(4).map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]])).collect();
    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(dir.join(format!("{name}.json"))).unwrap()).unwrap();
    let shape = meta["shape"].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect();
    (data, shape)
}

/// Model file from the benchmark folder (downloaded there, not committed). `None` skips the test.
pub fn bench_model(rel: &str) -> Option<PathBuf> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../bench/audio-enhance/models").join(rel);
    p.exists().then_some(p)
}

/// Scale-invariant SDR in dB.
pub fn si_sdr(reference: &[f32], estimate: &[f32]) -> f32 {
    let n = reference.len().min(estimate.len());
    let (r, e) = (&reference[..n], &estimate[..n]);
    let dot: f64 = r.iter().zip(e).map(|(a, b)| *a as f64 * *b as f64).sum();
    let rr: f64 = r.iter().map(|a| (*a as f64).powi(2)).sum();
    let alpha = dot / rr.max(1e-12);
    let (mut t, mut noise) = (0f64, 0f64);
    for (a, b) in r.iter().zip(e) {
        let target = alpha * *a as f64;
        t += target * target;
        noise += (*b as f64 - target).powi(2);
    }
    (10.0 * (t.max(1e-12) / noise.max(1e-12)).log10()) as f32
}
